### ISSUE TITLE
6. Revisão do Termo de Uso da Plataforma

### ISSUE THREAD

**Issue by aracele** [pauliceia/issues#8]
**Descrição da tarefa**

<Inserir descrição da tarefa aqui>

**Etapas da tarefa**

- [x] Estudar sugestões dos pareceres da Fapesp sobre isso
- [x] Estudar LGPD e verificar necessidades de adequações @matchboxxz @monalizacaetano 
- [x] Redigir nova proposta e submeter à equipe do Projeto

**Prioridade**
- [x] 1
- [x] 2
- [ ] 3

**Importante**: Não esquecer de se assinar à tarefa, assim como as demais pessoas envolvidas. Colocar _Labels_ (ex.: documentation) também é importante para a documentação. Usar "fase1.5" como _Milestone_. Fiquem à vontade também para adicionar mais informações que considerarem necessárias ao corpo desta issue.

**Comment by luisferla** [comment]
Dei uma olhada na LGPD. É meio complexa a coisa. No entanto, pelo que entendi, resolveríamos o problema incluindo em nosso Plano de Gestão de Dados e em nosso Termo de Uso duas coisas:

- informar ao usuário que dados são coletados e qual a motivação (no caso, nome, e-mail, senha e login)
- informar um canal de comunicação com os usuários.

Ainda pelo que entendi, os dados que o usuário alimentar na criação da camada não entrariam no escopo da lei, pois não seriam dados pessoais. Em todo caso, talvez precisemos tirar essa dúvida com alguém que entenda melhor do assunto.

**Comment by monalizacaetano** [comment]
Pessoal, posso ficar responsável pela escrita de uma primeira versão do informe ao usuário de que dados são coletados e qual a motivação (no caso, nome, e-mail, senha e login).

**Comment by matchboxxz** [comment]
Oi pessoal! hoje consegui dá uma pesquisada na lei e achei bem complexo também. Ainda achei algumas notícias e sites que detalhavam melhor, daí ficou mais entendível. Mas eu acho que as camadas entram como algo a ser protegido, principalmente para esclarecer aos usuários que os dados inseridos na plataforma permaneceram disponíveis enquanto a plataforma existir e deixar claro que se a exclusão dessas camadas não vai deixar alguns ''restos'' (ponto I - o respeito à privacidade). Um exemplo: quanto apagávamos camadas e elas não eram excluídas e não permitia domínio ao proprietário do dado. Tudo bem que é um bug, mas isso tem que ficar claro (ao meu ver). 
Outra coisa é: dei uma lida no que está disponível hoje na plataforma dos termos de uso e achei bem desatualizado, não tem muito respaldo de leis e nem citação sobre esse ser um projeto de ciência aberta. Posso ficar responsável por essa atualização e ajudar a Mona na escrita.

**Comment by luisferla** [comment]
Ótimo, Vitória! Sugestão aceita! Para essa nova versão do Termo, além da ajuda da Mona, seria importante coj=tejar com o que dizem os pareceristas do último despacho da Fapesp, ok? Alguns fizeram menção ao Termo. Obrigado! Vocês poderiam dar um prazo para a entrega dessa nova versão?

**Comment by matchboxxz** [comment]
Boa Ferla! vou pegar o parecer da Fapesp e começar a fazer essa atualização. O prazo pode ser semana que vem, dia 19 (segunda-feira)? Caso fique muito difícil/atrase eu aviso.

**Comment by luisferla** [comment]
Beleza, Vicka! O prazo é vc quem dá (e vc quem cumpre...rs).

Em 13/07/2021 19:24, Vitoria Martins Fontes escreveu:

**Comment by matchboxxz** [comment]
Pessoal! hoje fiquei a tarde inteira lendo, relendo e tentando entender melhor como adequar o documento ao a LGPD. Peguei como referência o Plano de gestão de dados que foi enviado e fiz algumas mudanças nesse novo documento <https://docs.google.com/document/d/1oW0DFKL_Ao-WrAuYGCY7SKvWPEC29oCz78ru7KHwOBE/edit?usp=sharing>. Estou bem insegura enquanto a isso porque eu realmente não sei se esse é o caminho certo/possível.

**Comment by matchboxxz** [comment]
Oi pessoal. Estava navegando no site do centro de pesquisa e formação do sesc e vai acontecer uma formação sobre a LGPD. Infelizmente é paga mas pensei em participar. Acham uma boa ideia? deixo o link aqui p q vocês vejam se vale a pena ou não https://centrodepesquisaeformacao.sescsp.org.br/atividade/lei-geral-de-protecao-de-dados-uma-imersao

**Comment by luisferla** [comment]
Qual o valor, Vitória? O Fundo Hímaco não é grandes coisas, mas tem uns 
500 reais lá.

Em 28/07/2021 16:11, Vitoria Martins Fontes escreveu:

**Comment by matchboxxz** [comment]
É 21 reais! peço a metade pro fundo hímaco.

**Comment by aracele** [comment]
> Dei uma olhada na LGPD. É meio complexa a coisa. No entanto, pelo que entendi, resolveríamos o problema incluindo em nosso Plano de Gestão de Dados e em nosso Termo de Uso duas coisas:
> 
>     * informar ao usuário que dados são coletados e qual a motivação (no caso, nome, e-mail, senha e login)
> 
>     * informar um canal de comunicação com os usuários.
> 
> 
> Ainda pelo que entendi, os dados que o usuário alimentar na criação da camada não entrariam no escopo da lei, pois não seriam dados pessoais. Em todo caso, talvez precisemos tirar essa dúvida com alguém que entenda melhor do assunto.

Acho que é basicamente isso! Além disso, até onde me lembro o usuário precisa ter a opção de poder excluir totalmente o cadastro e consequemente os dados dele do nosso banco de dados, ou seja, precisamos oferecer a ele a opção "excluir cadastro e dados". 

No caso das camadas acho que por razões óbvias, elas precisam ser tratadas como dados públicos, por isso é importante que nos termos a gente deixe claro isso pro usuário, que concordando com os termos ele estará concordando que aquela camada agora será um bem comum.

**Comment by matchboxxz** [comment]
Pessoal, reli as mensagens que foram trocadas aqui e pelo que eu entendi essa tarefa meio que já está fechada, certo? Pois a alteração no texto já existe, peço que revejam também para fecharmos se já foi feito ou não https://docs.google.com/document/d/1oW0DFKL_Ao-WrAuYGCY7SKvWPEC29oCz78ru7KHwOBE/edit?usp=sharing

**Comment by luisferla** [comment]
Beleza, Vicka. Aqui acho que já está quase fechando. Vou dar uma lida afinal, agora que reli os pareceres e tenho eles frescos na cabeça. Mas, antes, reitero que precisamos centralizar todos esse documentos em uma mesma pasta, em um drive, se não ficaremos malucos e mergulhados em n versões de cada coisa. Alguém se habilita para fazer isso?

**Comment by luisferla** [comment]
Coloquei uma niva versão dos Termos de Uso lá na pasta do Recurso 2. Na verdade, fiz apenas ajustes de padronização de redação. Não identifiquei o que mudar por conta da LGPD que já não tivesse no Plano de Dados. Aliás, Aracele disse duas coisas acima que, acredito, deva ser incluída no Plano de Dados, e não nos Termos de Uso:
 "Acho que é basicamente isso! Além disso, até onde me lembro o usuário precisa ter a opção de poder excluir totalmente o cadastro e consequemente os dados dele do nosso banco de dados, ou seja, precisamos oferecer a ele a opção "excluir cadastro e dados".

No caso das camadas acho que por razões óbvias, elas precisam ser tratadas como dados públicos, por isso é importante que nos termos a gente deixe claro isso pro usuário, que concordando com os termos ele estará concordando que aquela camada agora será um bem comum."

**Comment by luisferla** [comment]
Bom, como é melhor pecar por ecesso, acabei de inluir o item abaixo nos Termos de Uso. Vejam o que acham:

Sobre os dados alimentados à plataforma

O usuário colaborador que alimentar uma camada de dados à plataforma se declara ciente que a licença de compartilhamento dessas informações é a Creative Commons 4.0 (https://creativecommons.org/licenses/by/4.0/deed.pt_BR), que autoriza o compartilhamento e a adaptação do material acessado, com a necessidade de atribuição da origem à Plataforma Pauliceia 2.0.
Por outro lado, e em conformidade com a Lei Geral de Proteção de Dados Pessoais (Lei 13709, de 14 de agosto de 2018, disponível em http://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm), é facultado ao usuário o descredenciamento da plataforma, com o respectivo apagamento dos dados respectivos do seu banco de dados.
Mais informações e diretrizes com relação aos dados alimentados à plataforma estão no documento “Plano de Gestão de Dados”.

**Comment by luisferla** [comment]
Fechow!
