### ISSUE TITLE
4. Revisão do Plano de Gestão de Dados

### ISSUE THREAD

**Issue by aracele** [pauliceia/issues#9]
**Descrição da tarefa**

Revisar e reescrever o Plano de Gestão de Dados de modo a adequá-lo à [LGPD (Lei Geral de Proteção de Dados)](http://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm) e torná-lo também mais claro e objetivo.

**Etapas da tarefa**

- [x] Estudar a LGPD e definir que impactos ela poderia ter sobre a gestão de dados do Pauliceia + nome pessoa(s) a cargo dela. @luisferla @matchboxxz 
- [x] Estudar os pareceres da Fapesp e avaliar o que é pertinente incluir no Plano
- [x] Reescrever o plano usando a ferramenta [dmptool](https://dmptool.org/), conforme sugerido pela FAPESP + nome pessoa(s) a cargo dela
- [x] Submeter o novo plano para a equipe do projeto
- [x] Aprovar versão final após sugestões da equipe

**Prioridade**
- [x] 1
- [ ] 2
- [ ] 3

**Importante**: Não esquecer de se assinar à tarefa, assim como as demais pessoas envolvidas. Colocar _Labels_ (ex.: documentation) também é importante para a documentação. Usar "fase1.5" como _Milestone_. Fiquem à vontade também para adicionar mais informações que considerarem necessárias ao corpo desta issue.

**Comment by luisferla** [comment]
Dei uma olhada na LGPD. É meio complexa a coisa. No entanto, pelo que entendi, resolveríamos o problema incluindo em nosso Plano de Gestão de Dados e em nosso Termo de Conduta duas coisas:

- informar ao usuário que dados são coletados e qual a motivação (no caso, nome, e-mail, senha e login)
- informar um canal de comunicação com os usuários.

Ainda pelo que entendi, os dados que o usuário alimentar na criação da camada não entrariam no escopo da lei, pois não seriam dados pessoais. Em todo caso, talvez precisemos tirar essa dúvida com alguém que entenda melhor do assunto.

**Comment by luisferla** [comment]
Posso propor um cronograma para essa issue. Mas agora me dei conta de que não sei onde ponho isso. Entraria como mais um comentário? Luzes aracelianas disponíveis?

**Comment by matchboxxz** [comment]
Oi pessoal! acho que o cronograma pode ser descrito tipo ''data: assunto'', fica mais fácil. 
Escrevo para avisar que fiz o cadastro no dmptool e essa é uma plataforma realmente muito interessante e que facilita resolver o problema de falta de objetividade no texto. Como já criei a página para o pauliceia, vou adiciona-los como colaboradores, que pelo que entendi conseguem editar, sugerir e fazer a leitura do documento. Com relação aos pontos elencados no dmptool na escrita de plano, podemos discutir no GP ou fechar uma data para um GT, acho que fica mais fácil. 

Abrazos

**Comment by aracele** [comment]
> Posso propor um cronograma para essa issue. Mas agora me dei conta de que não sei onde ponho isso. Entraria como mais um comentário? Luzes aracelianas disponíveis?

Dá pra fazer isso cadastrando um novo "Milestone". O milestone dessa issue tá definido como sendo o 1.5, que é o milestone geral que criei pra todas as issues, mas nada impede (inclusive acho que pode até ser uma melhor forma de gerenciar) que criemos um específico pra esta daqui. 

Já existem instruções de como criar milestones no tutorial que criei: https://github.com/pauliceia/issues#passo-4---escolhendo-um-marco-temporal

**Comment by luisferla** [comment]
Alguém lembra o nome daquele site que ajuda a fazer plano de gestão de dados (é para uma amiga)?

**Comment by luisferla** [comment]
Já achei!

**Comment by matchboxxz** [comment]
Pessoal, essa reescrita eu já tinha iniciado mas parei no meio do caminho, ele realmente facilita mas ao mesmo tempo tem coisas que eu não sei como responder. No DMptoll tem vários exemplos de projetos da UNIFESP também, então dá pra pegar a referência. Vocês estão como editores no documento, já tinha enviado o convite por e-mail também.  Vou fazer a inclusão de algumas informações e logo menos listo aqui o que falta.

**Comment by luisferla** [comment]
Povo, como estamos já na tarefa de fazer o novo recurso, e como o PGD é um dos pontos principais dele, precisamos fechar essa issue. Perguntas: onde está a versão última do PGD? Acho que precisamos criar um drive do recurso, não? Confesso que estou meio perdido aqui.

**Comment by luisferla** [comment]
@matchboxxz, preciso da última versão desse documento. Criei uma pasta em nosso drive para centralizar todos os documentos para o recurso. Você envia o texto para mim e eu faço o upload lá, ok?

**Comment by luisferla** [comment]
Localizei o link do DMtool que a Vitória criou: https://dmptool.org/plans/67473. Vou trabalhar ali com o que já existe e o que demandam os pareceres, ok?

**Comment by luisferla** [comment]
Povo, elaborei a nova versão do PGD. Busquei cotejar com os pareceres e com a LGPD, e usei o DMtool criado pela Vitória.. Mas peço, por favor, que deem uma revisada no texto, principalmente nas partes mais computacionais. O arquivo está na pasta do drive do Recurso, e pode ser acessado em https://drive.google.com/file/d/1dqlU02qI6TgCGS72RwHcvwCSrhhxL4XQ/view?usp=sharing.

**Comment by luisferla** [comment]
Fechow!!
